name: vsum_eval
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - blosc=1.16.3=hf484d3e_0
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py37_0
  - cycler=0.10.0=py_1
  - dbus=1.13.2=h714fa37_1
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=hf484d3e_1002
  - ffmpeg=4.1.1=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=nompi_py37hf008753_1102
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - hdf5storage=0.1.15=py_1
  - icu=58.2=hf484d3e_1000
  - ipykernel=5.1.0=py37h24bf2e0_1002
  - ipython=7.4.0=py37h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.1=py37_0
  - jupyter_client=5.2.4=py_3
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.4=py37_0
  - jupyterlab_server=0.2.0=py_0
  - kiwisolver=1.0.1=py37h6bb024c_1002
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=4_openblas
  - libcblas=3.8.0=4_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=4_openblas
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.16=h14c3975_1001
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - lzo=2.10=h14c3975_1000
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.0.3=py37_0
  - matplotlib-base=3.0.3=py37h167e16e_0
  - mistune=0.8.4=py37h14c3975_1000
  - mock=2.0.0=py37_1001
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - notebook=5.7.8=py37_0
  - numexpr=2.6.9=py37h637b7d7_1000
  - numpy=1.16.2=py37h8b7e671_1
  - openblas=0.3.5=h9ac9557_1001
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1b=h14c3975_1
  - pandas=0.24.2=py37hf484d3e_0
  - pandoc=2.7.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.4.0=py_0
  - patsy=0.5.1=py_0
  - pbr=5.1.3=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.0.3=py37_0
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.3.1=py_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.6.0=py37h13b7fb3_1008
  - pyrsistent=0.14.11=py37h14c3975_0
  - pytables=3.5.1=py37h442f067_1
  - python=3.7.3=h5b0a415_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.1=py37h0e1adb2_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=hf8c457e_1001
  - scikit-learn=0.20.3=py37ha8026db_1
  - scikit-video=1.1.11=pyh24bf2e0_0
  - scipy=1.2.1=py37h09a28d5_1
  - seaborn=0.9.0=py_0
  - send2trash=1.5.0=py_0
  - setuptools=41.0.0=py37_0
  - sip=4.18.1=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.26.0=h67949de_1001
  - statsmodels=0.9.0=py37h3010b51_1000
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=h84994c4_1001
  - tornado=6.0.2=py37h516909a_0
  - traitlets=4.3.2=py37_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.1=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.2.5=hf484d3e_1006
  - zlib=1.2.11=h14c3975_1004